services:
  glasspi:
    build: .
    container_name: glasspi-dashboard
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    environment:
      - VITE_ADGUARD_URL=/adguard-api
      - VITE_KUMA_URL=/kuma-api
